name: meerai_mobile
description: MeeRaiKin - Daily meal suggestions with local notifications
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP Client
  dio: ^5.4.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Local Notifications
  flutter_local_notifications: ^16.3.2
  
  # Timezone Handling
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  
  # Images
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
